
macro(c23_test name)
add_executable(test_${name} tests/test_${name}.c)
target_link_libraries(test_${name} c23 m m23)
endmacro()

macro(c23_atf_test name VAR)
add_executable(t_${name} tests/t_${name}.c)
target_link_libraries(t_${name} c23 m m23 atf-c)
list(APPEND ${VAR} t_${name})
endmacro()

function(write_atf_file VAR)
set(atfheader "Content-Type: application/X-atf-atffile\; version=\"1\"\n\n")
set(atfprop "prop: test-suite = \"NetBSD-c23\"\n\n")
file(WRITE ${CMAKE_BINARY_DIR}/Atffile ${atfheader})
file(APPEND ${CMAKE_BINARY_DIR}/Atffile ${atfprop})
foreach(te IN LISTS ${VAR})
  file(APPEND ${CMAKE_BINARY_DIR}/Atffile "tp: ${te}\n")  
endforeach()
endfunction()
